apiVersion: v1
kind: Service
metadata:
  name: zomato-service
  namespace: zomato
spec:
  type: NodePort
  selector:
    app: zomato-clone
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30080
